name: generate PDF

on: workflow_dispatch

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git
        uses: actions/checkout@v3

      - name: Generate LaTex Files
        run: |
          cd tex
          python expander.py -l -r ../src

      - name: Compile Tex File
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: tex/out
          root_file: main.tex
          args: -pdf -pdfdvi -latex=uplatex -file-line-error -halt-on-error -interaction=nonstopmode
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Library
          path: tex/out/main.pdf
